apiVersion: v1
kind: Service
metadata:
name: django-messaging-service
spec:
type: ClusterIP
selector:
app: django-messaging-blue # Initially points to blue deployment
ports:
- protocol: TCP
port: 80
targetPort: 8000